version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: newsapp
      POSTGRES_PASSWORD: "Zofb-3pIZ5vYz2h-xHaTVzrHOlke8co1"
    volumes:
      - newsapp_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "DV2euwoY9jdn3CzwD2-lMOfIdgJOb0Gl"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  newsapp_data:
